# .streamlit/secrets.toml

[connections.neon]
url="postgresql://neondb_owner:npg_vmwlLkO2Hc0U@ep-plain-butterfly-an0vn9g7-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"